### ISSUE TITLE
[Bug] Community Activity page Pull2Refresh crashes App.

### ISSUE THREAD

**Issue by CliffAgius** [sthewissen/MVP#123]
When running on Android Emulator and Device if you pull-to-refresh the Community Activities list the App crashes.

Exception raised is:

    System.ObjectDisposedException: 'Cannot access a disposed object.
    Object name: 'Xamarin.Forms.Platform.Android.RefreshViewRenderer'.'

This needs investigation and fixing.

Using VS22 Preview 4.1
Emulator Pixel 3A running Android Q
Device Pixel 4XL running Android R

**Comment by sthewissen** [comment]
This RefreshView in there is going to be the death of me.
