### ISSUE TITLE
[Feature] App Translations Needed :)

### ISSUE THREAD

**Issue by sthewissen** [sthewissen/MVP#23]
The MVP community is a global affair. Multi-language support should be in there!

- [x] Add multi-language infrastructure
- [x] Set up English language
- [x] Add additional languages

## The process

1. Post below which language you'd like to create translations for so we don't have duplicate work being done.
2. Make a copy of the `Translations.resx` and `Translations.Designer.cs` files located in the `Resources` folder. 
3. Rename it so that it is suffixed with the appropriate culture name for the language you're adding (e.g. `Translations.nl.resx`).
4. Translate all the English texts to the language you're adding.
5. Add an entry in `LanguagePickerViewModel` adding your language using its CI name.

```
public List<string> supportedLanguages = new List<string> { "en", "nl", "es", "sv" };
```

6. Create a nice and shiny PR to add it to the app! 🎉❤️

## Volunteers

- [x] German - @mallibone
- [x] Spanish - @keozx
- [x] Turkish - @cihanyakar
- [x] French - @ewinnington / @pioup
- [x] Swedish - @bjorndaniel 
- [x] Hungarian - @mkanyo
- [x] Norwegian - @rickdijk
- [x] Italian - @acaliaro
- [x] Bosnian - @almirvuk
- [ ] Portuguese - Jhonatan Oliveira / Paulo Carvalho

**Comment by mallibone** [comment]
Hey Steven, happy to contribute ze German translation. 🙂

**Comment by keozx** [comment]
Doing Spanish now 😁

**Comment by cihanyakar** [comment]
I have started translating into Turkish

**Comment by ewinnington** [comment]
Working on the French.

**Comment by pioup** [comment]
@ewinnington if you need help for French I am up to it

**Comment by ewinnington** [comment]
> @ewinnington if you need help for French I am up to it

I’ll tag you to review when I PR it. _Merci_

**Comment by bjorndaniel** [comment]
I can do Swedish

**Comment by mkanyo** [comment]
I'll do Hungarian 🤓

**Comment by rickdijk** [comment]
I'll start at Norwegian this week 😇

**Comment by acaliaro** [comment]
Try with Italian

**Comment by almirvuk** [comment]
I will do the Bosnian, bs-Latn-BA 🙂

**Comment by sthewissen** [comment]
I have one more line I would want to get translated (sorry for coming up with that late). I'll do all the code work, so would just need a reply here whether or not this is correct or if a correction is needed. Thanks in advance!

Here's the line:
> Please reboot the application for your language change to take effect.

French (@ewinnington @pioup):
> Veuillez redémarrer l'application pour que votre changement de langue prenne effet.

Spanish (@keozx @luispujols)
> Reinicie la aplicación para que se aplique el cambio de idioma.

Bosnian (@almirvuk)
> Ponovo pokrenite aplikaciju da bi vaša promjena jezika stupila na snagu.

Swedish (@bjorndaniel)
> Starta om applikationen för att din språkändring ska träda i kraft.

Italian (@acaliaro)
> Riavvia l'applicazione affinché la modifica della lingua abbia effetto.

Turkish (@cihanyakar)
> Dil değişikliğinizin geçerli olması için lütfen uygulamayı yeniden başlatın.

Norwegian (@rickdijk)
> Start programmet på nytt for at språkendringen skal tre i kraft.

Hungarian (@mkanyo)
> Kérjük, indítsa újra az alkalmazást, hogy a nyelvváltozás életbe lépjen.

**Comment by almirvuk** [comment]
That is correct translation 😊

**Comment by acaliaro** [comment]
per me è ok

**Comment by pioup** [comment]
The translation is correct. La traduction est correcte.  😊

**Comment by keozx** [comment]
Spanish good 👍

**Comment by rickdijk** [comment]
Norwegian is correct

**Comment by mkanyo** [comment]
Hungarian - Sorry, I used "informal" addressing all along and yours is
quite right but it's formal. So this is the "informal" version. Don't worry
when I say informal it's quite normal really for anyone under 75 🙂

Kérlek, indítsd újra az alkalmazást, hogy a nyelvváltozás életbe lépjen.

Cheers,
Miklos
