### ISSUE TITLE
[Feature] Show your MVP profile

### ISSUE THREAD

**Issue by sthewissen** [sthewissen/MVP#3]
### What?
- Shows the MVP's own profile consisting of:
   - ✅ Picture
   - ~Biography~
   - ~Country~
   - ✅ Headline
   - ~Number of awards~
   - ~Year first awarded~

### Optional
- ~Show the list of online identities of the MVP.~
- ~Show the username and use e.g. FontAwesome to show an icon of the social platform.~
- ~Swipe left deletes an identity.~
- ~Tapping it opens the edit view.~
- ~A button allows the user to add a new online identity.~

**Comment by almirvuk** [comment]
Can I work on this one? 🙂

**Comment by sthewissen** [comment]
You sure can!

**Comment by sthewissen** [comment]
Can probably collapse this with #22

**Comment by sthewissen** [comment]
Only thing needed here is to figure out the best way to cache this data.

**Comment by sthewissen** [comment]
Caching this for 14 days, and allowing the user to refresh it by tapping on it.
